web:
  // 1 Hour
  max_age: 3600
  index_file: "index.html"
  data_path: "./web"
  port: 8080
  bind: 0.0.0.0
  proxy_header: "X-Forwarded-For"
  trusted_proxies: ["127.0.0.1", "198.41.192.7"]

seo:
  data_path: "./seo"
  geo_header: "CF-IPCountry"
  languages:
    en:
      default: true
      country: []
    id:
      country: ["ID", "MY"]